// serviceWorker.js - v037 battle prototype cache clear対応版
const CACHE_NAME = "tenotsu-v037-77-root-root";
const URLS_TO_CACHE = [
  "./",
  "./index.html",
  "./images/assets/char/m11201.webp",
  "./images/assets/char/m11101.webp",
  "./images/assets/char/m11002.webp",
  "./images/assets/char/m11001.webp",
  "./images/assets/char/m10902.webp",
  "./images/assets/char/m10901.webp",
  "./images/assets/char/m10801.webp",
  "./images/assets/char/m10701.webp",
  "./images/assets/char/m10601.webp",
  "./images/assets/char/m10501.webp",
  "./images/assets/char/m10401.webp",
  "./images/assets/char/m10301.webp",
  "./images/assets/char/m10201.webp",
  "./images/assets/char/m10101.webp",
  "./images/assets/char/l11201.webp",
  "./images/assets/char/l11101.webp",
  "./images/assets/char/l11001.webp",
  "./images/assets/char/l10901.webp",
  "./images/assets/char/l10801.webp",
  "./images/assets/char/l10701.webp",
  "./images/assets/char/l10601.webp",
  "./images/assets/char/l10501.webp",
  "./images/assets/char/l10401.webp",
  "./images/assets/char/l10301.webp",
  "./images/assets/char/l10201.webp",
  "./images/assets/char/l10101.webp",
  "./images/assets/char/k11301.webp",
  "./images/assets/char/k11201.webp",
  "./images/assets/char/k11101.webp",
  "./images/assets/char/k11001.webp",
  "./images/assets/char/k10901.webp",
  "./images/assets/char/k10801.webp",
  "./images/assets/char/k10702.webp",
  "./images/assets/char/k10701.webp",
  "./images/assets/char/k10601.webp",
  "./images/assets/char/k10501.webp",
  "./images/assets/char/k10401.webp",
  "./images/assets/char/k10301.webp",
  "./images/assets/char/k10202.webp",
  "./images/assets/char/k10201.webp",
  "./images/assets/char/k10102.webp",
  "./images/assets/char/k10101.webp",
  "./images/assets/char/j11201.webp",
  "./images/assets/char/j11101.webp",
  "./images/assets/char/j11001.webp",
  "./images/assets/char/j10901.webp",
  "./images/assets/char/j10801.webp",
  "./images/assets/char/j10701.webp",
  "./images/assets/char/j10602.webp",
  "./images/assets/char/j10601.webp",
  "./images/assets/char/j10501.webp",
  "./images/assets/char/j10401.webp",
  "./images/assets/char/j10301.webp",
  "./images/assets/char/j10201.webp",
  "./images/assets/char/j10102.webp",
  "./images/assets/char/j10101.webp",
  "./images/assets/char/i11301.webp",
  "./images/assets/char/i11201.webp",
  "./images/assets/char/i11101.webp",
  "./images/assets/char/i11001.webp",
  "./images/assets/char/i10901.webp",
  "./images/assets/char/i10801.webp",
  "./images/assets/char/i10701.webp",
  "./images/assets/char/i10602.webp",
  "./images/assets/char/i10601.webp",
  "./images/assets/char/i10501.webp",
  "./images/assets/char/i10401.webp",
  "./images/assets/char/i10301.webp",
  "./images/assets/char/i10202.webp",
  "./images/assets/char/i10201.webp",
  "./images/assets/char/i10101.webp",
  "./images/assets/char/h11401.webp",
  "./images/assets/char/h11302.webp",
  "./images/assets/char/h11301.webp",
  "./images/assets/char/h11202.webp",
  "./images/assets/char/h11201.webp",
  "./images/assets/char/h11101.webp",
  "./images/assets/char/h11001.webp",
  "./images/assets/char/h10901.webp",
  "./images/assets/char/h10801.webp",
  "./images/assets/char/h10701.webp",
  "./images/assets/char/h10601.webp",
  "./images/assets/char/h10501.webp",
  "./images/assets/char/h10401.webp",
  "./images/assets/char/h10301.webp",
  "./images/assets/char/h10202.webp",
  "./images/assets/char/h10201.webp",
  "./images/assets/char/h10101.webp",
  "./images/assets/char/g11401.webp",
  "./images/assets/char/g11301.webp",
  "./images/assets/char/g11201.webp",
  "./images/assets/char/g11101.webp",
  "./images/assets/char/g11001.webp",
  "./images/assets/char/g10701.webp",
  "./images/assets/char/g10601.webp",
  "./images/assets/char/g10501.webp",
  "./images/assets/char/g10401.webp",
  "./images/assets/char/g10201.webp",
  "./images/assets/char/g10101.webp",
  "./images/assets/char/f11201.webp",
  "./images/assets/char/f11101.webp",
  "./images/assets/char/f11001.webp",
  "./images/assets/char/f10901.webp",
  "./images/assets/char/f10801.webp",
  "./images/assets/char/f10702.webp",
  "./images/assets/char/f10701.webp",
  "./images/assets/char/f10601.webp",
  "./images/assets/char/f10501.webp",
  "./images/assets/char/f10402.webp",
  "./images/assets/char/f10401.webp",
  "./images/assets/char/f10301.webp",
  "./images/assets/char/f10202.webp",
  "./images/assets/char/f10201.webp",
  "./images/assets/char/f10102.webp",
  "./images/assets/char/f10101.webp",
  "./images/assets/char/e11201.webp",
  "./images/assets/char/e11101.webp",
  "./images/assets/char/e11001.webp",
  "./images/assets/char/e10901.webp",
  "./images/assets/char/e10801.webp",
  "./images/assets/char/e10702.webp",
  "./images/assets/char/e10701.webp",
  "./images/assets/char/e10601.webp",
  "./images/assets/char/e10501.webp",
  "./images/assets/char/e10401.webp",
  "./images/assets/char/e10301.webp",
  "./images/assets/char/e10201.webp",
  "./images/assets/char/e10101.webp",
  "./images/assets/char/d11301.webp",
  "./images/assets/char/d11101.webp",
  "./images/assets/char/d11001.webp",
  "./images/assets/char/d10901.webp",
  "./images/assets/char/d10802.webp",
  "./images/assets/char/d10801.webp",
  "./images/assets/char/d10701.webp",
  "./images/assets/char/d10602.webp",
  "./images/assets/char/d10601.webp",
  "./images/assets/char/d10501.webp",
  "./images/assets/char/d10401.webp",
  "./images/assets/char/d10303.webp",
  "./images/assets/char/d10302.webp",
  "./images/assets/char/d10301.webp",
  "./images/assets/char/d10201.webp",
  "./images/assets/char/d10101.webp",
  "./images/assets/char/d10101.png",
  "./images/assets/char/c19901.webp",
  "./images/assets/char/c11302.webp",
  "./images/assets/char/c11301.webp",
  "./images/assets/char/c11202.webp",
  "./images/assets/char/c11201.webp",
  "./images/assets/char/c11102.webp",
  "./images/assets/char/c11101.webp",
  "./images/assets/char/c11001.webp",
  "./images/assets/char/c10902.webp",
  "./images/assets/char/c10801.webp",
  "./images/assets/char/c10702.webp",
  "./images/assets/char/c10701.webp",
  "./images/assets/char/c10601.webp",
  "./images/assets/char/c10502.webp",
  "./images/assets/char/c10501.webp",
  "./images/assets/char/c10401.webp",
  "./images/assets/char/c10301.webp",
  "./images/assets/char/c10201.webp",
  "./images/assets/char/c10103.webp",
  "./images/assets/char/c10101.webp",
  "./images/assets/char/b11202.webp",
  "./images/assets/char/b11201.webp",
  "./images/assets/char/b11101.webp",
  "./images/assets/char/b11001.webp",
  "./images/assets/char/b10901.webp",
  "./images/assets/char/b10801.webp",
  "./images/assets/char/b10701.webp",
  "./images/assets/char/b10601.webp",
  "./images/assets/char/b10501.webp",
  "./images/assets/char/b10401.webp",
  "./images/assets/char/b10301.webp",
  "./images/assets/char/b10201.webp",
  "./images/assets/char/b10101.webp",
  "./images/assets/char/a11201.webp",
  "./images/assets/char/a11101.webp",
  "./images/assets/char/a11001.webp",
  "./images/assets/char/a10901.webp",
  "./images/assets/char/a10802.webp",
  "./images/assets/char/a10801.webp",
  "./images/assets/char/a10701.webp",
  "./images/assets/char/a10602.webp",
  "./images/assets/char/a10601.webp",
  "./images/assets/char/a10501.webp",
  "./images/assets/char/a10402.webp",
  "./images/assets/char/a10401.webp",
  "./images/assets/char/a10302.webp",
  "./images/assets/char/a10301.webp",
  "./images/assets/char/a10202.webp",
  "./images/assets/char/a10102.webp",
  "./images/assets/char/a10101.webp",
  "./program/docs/expression_master.md",
  "./scenario/listmenu/expression_master.json",
  "./scenario/data/character_expressions.json",
  "./scenario/scenario/intro_moe.json",
  "./scenario/scenario/intro_satomi.json",
  "./scenario/scenario/intro_ayame.json",
  "./scenario/scenario/intro_momo.json",
  "./scenario/scenario/intro_yozora.json",
  "./scenario/scenario/intro_misora.json",
  "./scenario/scenario/intro_yukino.json",
  "./scenario/scenario/intro_manaka.json",
  "./scenario/scenario/intro_kohaku.json",
  "./scenario/scenario/intro_kogane.json",
  "./scenario/scenario/intro_midori.json",
  "./scenario/scenario/intro_ai.json",
  "./scenario/scenario/intro_hina.json",
  "./scenario/listmenu/intro_scenarios.json",
  "./scenario/listmenu/shop.json",
  "./program/docs/story_memory.md",
  "./program/docs/menu_layout.md",
  "./program/docs/release_notes.md",
  "./README_GITHUB_LAYOUT.md",
  "./scenario/listmenu/menu01.json",
  "./scenario/listmenu/title_return_archive.json",
  "./scenario/listmenu/members.json",
  "./scenario/listmenu/member_list.json",
  "./images/assets/ev/ev_rooftop.png",
  "./images/assets/ev/ev01.png",
  "./images/assets/ev/a01ev05.png",
  "./images/assets/ev/a01ev04.png",
  "./images/assets/ev/a01ev03.png",
  "./images/assets/ev/a01ev02.png",
  "./scenario/random/imageset01.json",
  "./images/assets/bgev/logofusen.png",
  "./images/assets/bgev/bg_school.jpg",
  "./images/assets/bgev/bg_rooftop.jpg",
  "./images/assets/bgev/bg_library.jpg",
  "./images/assets/bgev/bg_field.jpg",
  "./images/assets/bgev/bg_beach.jpg",
  "./images/assets/bgev/bg020.jpg",
  "./images/assets/bgev/bg011.jpg",
  "./images/assets/bgev/title.jpg",
  "./scenario/listmenu/mainmenu.json",
  "./scenario/listmenu/office6.json",
  "./scenario/scenario/000start.json",
  "./program/style.css",
  "./program/chardispsetting.css",
  "./program/config.js",
  "./program/characterStyles.js",
  "./program/effect.js",
  "./program/menuList.js",
  "./program/randomShows.js",
  "./program/utils.js",
  "./program/script.js",
  "./program/battle.js",
  "./scenario/scenario/listmenu/office6.json",
  "./scenario/scenario/listmenu/office5.json",
  "./images/assets/cutin/cutin_hina_test.png",
  "./images/assets/character/card_hina_test.png",
  "./images/assets/cutin/cutin_moe_test.png",
  "./images/assets/character/card_moe_test.png",
  "./images/assets/cutin/cutin_satomi_test.png",
  "./images/assets/character/card_satomi_test.png",
  "./images/assets/cutin/cutin_ayame_test.png",
  "./images/assets/character/card_ayame_test.png",
  "./images/assets/cutin/cutin_momo_test.png",
  "./images/assets/character/card_momo_test.png",
  "./images/assets/cutin/cutin_yozora_test.png",
  "./images/assets/character/card_yozora_test.png",
  "./images/assets/cutin/cutin_misora_test.png",
  "./images/assets/character/card_misora_test.png",
  "./images/assets/cutin/cutin_yukino_test.png",
  "./images/assets/character/card_yukino_test.png",
  "./images/assets/cutin/cutin_manaka_test.png",
  "./images/assets/character/card_manaka_test.png",
  "./images/assets/cutin/cutin_kohaku_test.png",
  "./images/assets/character/card_kohaku_test.png",
  "./images/assets/cutin/cutin_kogane_test.png",
  "./images/assets/character/card_kogane_test.png",
  "./images/assets/cutin/cutin_midori_test.png",
  "./images/assets/character/card_midori_test.png",
  "./images/assets/cutin/cutin_ai_test.png",
  "./images/assets/character/card_ai_test.png",
  "./images/assets/enemy/enemy_marshmallow_massage_test.png",
  "./images/assets/enemy/enemy_donut_washer_test.png",
  "./images/assets/enemy/enemy_mochimochi_register_test.png",
  "./images/assets/enemy/enemy_game_potato_test.png",
  "./images/assets/enemy/enemy_jelly_humidifier_test.png",
  "./images/assets/enemy/enemy_kakigori_aircon_test.png",
  "./images/assets/enemy/enemy_pudding_oven_test.png",
  "./images/assets/enemy/enemy_beauty_macaron_test.png",
  "./images/assets/enemy/enemy_earphone_gummy_test.png",
  "./images/assets/enemy/enemy_smartphone_candy_test.png",
  "./images/assets/enemy/enemy_pc_pizza_test.png",
  "./images/assets/enemy/enemy_choco_dryer_test.png",
  "./images/assets/enemy/enemy_tv_popcorn_test.png",
  "./images/assets/bg/battle_store_lv1.png",
  "./images/assets/cutin/aa_hina_skill_cutin_test.png",
  "./images/assets/card/aa_hina_card_test.png",
  "./program/manifest.json",
  "./program/favicon.ico",
  "./program/favicon.png",
  "./program/icon-192.png",
  "./program/icon-512.png",
  "./scenario/scenario/random/imageset01.json",
  "./scenario/scenario/random/textset01.json",
  "./scenario/scenario/scenario/000start.json",
  "./scenario/scenario/scenario/gamestart.json",
  "./scenario/scenario/listmenu/title.json",
  "./scenario/scenario/listmenu/menu01.json",
  "./scenario/scenario/listmenu/list01.json",
  "./scenario/scenario/listmenu/mainmenu.json",
  "./scenario/scenario/listmenu/home.json",
  "./scenario/scenario/listmenu/members.json",
  "./scenario/scenario/listmenu/shop.json",
  "./scenario/scenario/scenario/town_placeholder.json",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(URLS_TO_CACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "CLEAR_CACHE") {
    event.waitUntil(
      caches.keys().then((keys) => Promise.all(keys.map((key) => caches.delete(key))))
    );
  }
});

function isCoreFile(url) {
  return /\.(html|css|js|json|webmanifest)$/i.test(url.pathname) || url.pathname.endsWith("/");
}

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  const url = new URL(event.request.url);

  // HTML/CSS/JS/JSONは更新確認しやすいようにネットワーク優先。
  // オフライン時だけキャッシュを返す。
  if (isCoreFile(url)) {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
          return response;
        })
        .catch(() => caches.match(event.request))
    );
    return;
  }

  // 画像・音声などはキャッシュ優先。
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        const copy = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        return response;
      });
    })
  );
});
