/* v039_124 story index: normal encounter / member key-main slots / recollection */
(function(){
  "use strict";
  window.TENOTSU_STORY_INDEX = [
    {
      id: "kogane_natsu_marinpia",
      title: "マリンピアの海中トンネル",
      type: "normal",
      category: "town_encounter",
      season: "summer",
      placeId: "marinpia_aqua_tunnel",
      placeName: "マリンピア・海中トンネル",
      characters: ["ad", "bc"],
      characterNames: ["小麦沢 こがね", "日向 なつ"],
      scenario: "scenario/v039/events/kogane_natsu_marinpia.json",
      version: "v039_105",
      unlock: { type: "always" },
      encounter: { enabled: true, staminaCost: 10, revealItem: "visitor_scope", seasonItem: "season_ticket" },
      order: 105,
      summary: "こがねとなつと一緒に、マリンピアの海中トンネルを見に行く夏の外回りイベント。"
    },
    {
      id: "sample_hina_kogane_new_juice_002",
      title: "事務所にて緋奈＆こがね：新作ジュースは何の味？",
      type: "normal",
      category: "office",
      placeId: "hidamari_office",
      placeName: "ひだまりストア・事務所",
      characters: ["aa", "ad", "ac"],
      characterNames: ["星野 緋奈", "小麦沢 こがね", "草壁 翠"],
      scenario: "scenario/v039/events/sample_hina_kogane_new_juice_002.json",
      version: "v039_106",
      unlock: { type: "always" },
      encounter: { enabled: false },
      order: 106,
      summary: "事務所の新作ジュースをきっかけに、緋奈が照れて、こがねが無邪気にかき回し、翠が締める日常会話。"
    },
    {
      id: "yozora_affection_00_01_key",
      title: "美空なら休憩室",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 1,
      affectionSlot: "key1",
      unlockLevel: 1,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_00_01_key.json",
      version: "v039_114",
      unlock: { type: "affection_level", character: "ai", level: 1 },
      order: 3001,
      summary: "夜空がまだ店長に距離を置き、自分ではなく美空を見てほしいと示す序盤キーストーリー。"
    },
    {
      id: "yozora_affection_00_02_key",
      title: "見てるだけ",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 1,
      affectionSlot: "key2",
      unlockLevel: 4,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_00_02_key.json",
      version: "v039_114",
      unlock: { type: "affection_level", character: "ai", level: 4 },
      order: 3002,
      summary: "美空の接客を夜空が横から自然にフォローし、自分は見ているだけだと距離を取る夜空キーシナリオ第2話。"
    },
    {
      id: "yozora_affection_00_03_key",
      title: "特別公演のチケット",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 1,
      affectionSlot: "key3",
      unlockLevel: 7,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_00_03_key.json",
      version: "v039_116",
      unlock: { type: "affection_level", character: "ai", level: 7 },
      order: 3003,
      summary: "星見ヶ丘プラネタリウムの特別公演を前に、夜空が美空の付き添いとして同行を決めるキーシナリオ第3話。"
    },
    {
      id: "yozora_affection_10_00_main",
      title: "余計なところまで見ないで",
      type: "main",
      category: "character_main",
      character: "ai",
      route: "yozora",
      affectionBlock: 1,
      affectionSlot: "main",
      unlockLevel: 10,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_10_00_main.json",
      version: "v039_116",
      unlock: {
        type: "all_story_cleared",
        storyIds: ["yozora_affection_00_01_key", "yozora_affection_00_02_key", "yozora_affection_00_03_key"],
        fallback: { type: "affection_level", character: "ai", level: 10 }
      },
      order: 3010,
      summary: "キー1-1〜1-3の伏線を受け、プラネタリウムで夜空が自分を見られることを意識し始めるメイン1。"
    }
    ,
    {
      id: "yozora_affection_10_01_key",
      title: "そういうの、気づかなくていい",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 2,
      affectionSlot: "key1",
      unlockLevel: 11,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_10_01_key.json",
      version: "v039_117",
      unlock: { type: "affection_level", character: "ai", level: 11 },
      order: 3011,
      summary: "プラネタリウム後、店長が夜空の細かな気遣いに気づき始め、夜空が『気づかなくていい』と拒むキーシナリオ。"
    },
    {
      id: "yozora_affection_10_02_key",
      title: "美空だけでいいでしょ",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 2,
      affectionSlot: "key2",
      unlockLevel: 14,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_10_02_key.json",
      version: "v039_117",
      unlock: { type: "affection_level", character: "ai", level: 14 },
      order: 3012,
      summary: "地域フェスの記念撮影で、夜空が見られる側になることや美空と比較されることを避けるキーシナリオ。"
    },
    {
      id: "yozora_affection_10_03_key",
      title: "気づかなくていい疲れ",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 2,
      affectionSlot: "key3",
      unlockLevel: 17,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_10_03_key.json",
      version: "v039_117",
      unlock: { type: "affection_level", character: "ai", level: 17 },
      order: 3013,
      summary: "閉店後の帰り道、夜空が美空の疲れには気づく一方、自分の寒さや疲れを見られることを嫌がるキーシナリオ。"
    },
    {
      id: "yozora_affection_20_00_main",
      title: "一歩後ろの夜空",
      type: "main",
      category: "character_main",
      character: "ai",
      route: "yozora",
      affectionBlock: 2,
      affectionSlot: "main",
      unlockLevel: 20,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_20_00_main.json",
      version: "v039_117",
      unlock: {
        type: "all_story_cleared",
        storyIds: ["yozora_affection_10_00_main", "yozora_affection_10_01_key", "yozora_affection_10_02_key", "yozora_affection_10_03_key"],
        fallback: { type: "affection_level", character: "ai", level: 20 }
      },
      order: 3020,
      summary: "潮見浜で、美空の一歩後ろにいる夜空の理由と、店長が夜空本人を見る違和感を掘り下げるメイン2。"
    }
    ,
    {
      id: "yozora_affection_20_01_key",
      title: "黒いリボン",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 3,
      affectionSlot: "key1",
      unlockLevel: 21,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_20_01_key.json",
      version: "v039_122",
      unlock: { type: "affection_level", character: "ai", level: 21 },
      order: 3021,
      summary: "夜空が黒いリボンを通して、美空が白なら自分は黒でいいと語り、白黒対比の原点に触れるキーシナリオ。"
    },
    {
      id: "yozora_affection_20_02_key",
      title: "夜空らしいって何",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 3,
      affectionSlot: "key2",
      unlockLevel: 24,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_20_02_key.json",
      version: "v039_122",
      unlock: { type: "affection_level", character: "ai", level: 24 },
      order: 3022,
      summary: "夜空が弓道を通して、反対を選んだだけなのか、それとも自分のものになっているのか揺れ始めるキーシナリオ。"
    },
    {
      id: "yozora_affection_20_03_key",
      title: "白と黒の飲み物",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 3,
      affectionSlot: "key3",
      unlockLevel: 27,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_20_03_key.json",
      version: "v039_122",
      unlock: { type: "affection_level", character: "ai", level: 27 },
      order: 3023,
      summary: "ブラックコーヒーとホットミルクを通じて、夜空が美空の反対を選ぶ癖と、同じものを選ぶ揺らぎを見せるキーシナリオ。"
    },
    {
      id: "yozora_affection_30_00_main",
      title: "白黒ツインルーム",
      type: "main",
      category: "character_main",
      character: "ai",
      route: "yozora",
      affectionBlock: 3,
      affectionSlot: "main",
      unlockLevel: 30,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_30_00_main.json",
      version: "v039_122",
      unlock: {
        type: "all_story_cleared",
        storyIds: ["yozora_affection_20_00_main", "yozora_affection_20_01_key", "yozora_affection_20_02_key", "yozora_affection_20_03_key"],
        fallback: { type: "affection_level", character: "ai", level: 30 }
      },
      order: 3030,
      summary: "双沢姉妹の白黒ツインルームで、夜空が美空の反対を選んできた自分と、それでも自分のものになったものへ向き合うメイン3。"
    }
    ,
    {
      id: "yozora_affection_30_01_key",
      title: "美空が褒められるのは嬉しい",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 4,
      affectionSlot: "key1",
      unlockLevel: 31,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_30_01_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 31 },
      order: 3031,
      summary: "美空が常連客に褒められ、夜空が嬉しさと小さな痛みの両方を抱くキーシナリオ。"
    },
    {
      id: "yozora_affection_30_02_key",
      title: "美空の剣道の方がわかりやすい",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 4,
      affectionSlot: "key2",
      unlockLevel: 34,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_30_02_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 34 },
      order: 3032,
      summary: "夜空の弓道をめぐり、美空の剣道への尊敬と自分が見られることへの抵抗を描くキーシナリオ。"
    },
    {
      id: "yozora_affection_30_03_key",
      title: "別にいい",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 4,
      affectionSlot: "key3",
      unlockLevel: 37,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_30_03_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 37 },
      order: 3033,
      summary: "夜空が接客で成果を出すが、話題が美空に流れることで嬉しさと痛みが混ざるキーシナリオ。"
    },
    {
      id: "yozora_affection_40_00_main",
      title: "嬉しいのに、苦しい",
      type: "main",
      category: "character_main",
      character: "ai",
      route: "yozora",
      affectionBlock: 4,
      affectionSlot: "main",
      unlockLevel: 40,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_40_00_main.json",
      version: "v039_124",
      unlock: {
        type: "all_story_cleared",
        storyIds: ["yozora_affection_30_00_main", "yozora_affection_30_01_key", "yozora_affection_30_02_key", "yozora_affection_30_03_key"],
        fallback: { type: "affection_level", character: "ai", level: 40 }
      },
      order: 3040,
      summary: "武道イベントで、美空の華やかな剣道と夜空の静かな弓道を対比し、夜空が嬉しいのに苦しい感情を漏らすメイン4。"
    },
    {
      id: "yozora_affection_40_01_key",
      title: "美空のところに行けば",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 5,
      affectionSlot: "key1",
      unlockLevel: 41,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_40_01_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 41 },
      order: 3041,
      summary: "メイン4後の反動で、夜空が店長を避けながら『美空のところに行けば』と自分から目を逸らさせようとするキーシナリオ。"
    },
    {
      id: "yozora_affection_40_02_key",
      title: "あんたが追ってくるだけ",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 5,
      affectionSlot: "key2",
      unlockLevel: 44,
      characters: ["ai"],
      characterNames: ["双沢 夜空"],
      scenario: "scenario/v039/events/yozora_affection_40_02_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 44 },
      order: 3042,
      summary: "駅前で夜空があからさまに店長を避け、『避けてない。あんたが追ってくるだけ』と距離を取るキーシナリオ。"
    },
    {
      id: "yozora_affection_40_03_key",
      title: "美空の大事なものなのに",
      type: "key",
      category: "character_key",
      character: "ai",
      route: "yozora",
      affectionBlock: 5,
      affectionSlot: "key3",
      unlockLevel: 47,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_40_03_key.json",
      version: "v039_124",
      unlock: { type: "affection_level", character: "ai", level: 47 },
      order: 3043,
      summary: "双沢姉妹の部屋で、夜空が店長に見つけてほしい気持ちと美空への罪悪感を美空に打ち明けるキーシナリオ。"
    },
    {
      id: "yozora_affection_50_00_main",
      title: "探さないで、の前兆",
      type: "main",
      category: "character_main",
      character: "ai",
      route: "yozora",
      affectionBlock: 5,
      affectionSlot: "main",
      unlockLevel: 50,
      characters: ["ai", "ah"],
      characterNames: ["双沢 夜空", "双沢 美空"],
      scenario: "scenario/v039/events/yozora_affection_50_00_main.json",
      version: "v039_124",
      unlock: {
        type: "all_story_cleared",
        storyIds: ["yozora_affection_40_00_main", "yozora_affection_40_01_key", "yozora_affection_40_02_key", "yozora_affection_40_03_key"],
        fallback: { type: "affection_level", character: "ai", level: 50 }
      },
      order: 3050,
      summary: "夜空が店長に『ぼくがいなくなっても、探さないで』と告げ、見つけてほしい矛盾を抱えたまま次章へ進むメイン5。"
    }



  ];
})();
